modLoader = "javafml" #mandatory
loaderVersion = "[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "CoFH \"Don't Be a Jerk\" License"
[[mods]] #mandatory
modId = "hussein" #mandatory
version = "1.1.2" #mandatory
displayName = "Hussein's Mod" #mandatory
description = '''
Just a mod for me and friends :D
'''
[[dependencies.hussein]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[47,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.hussein]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hussein]]
modId = "ae2"
versionRange = "[15.0.9-beta,)"
mandatory = true
ordering = "AFTER"
side = "BOTH"
[[dependencies.hussein]]
modId="codechickenlib"
mandatory=true
versionRange="4.4.0.+"
ordering="AFTER"
side="BOTH"
[[dependencies.hussein]]
modId="brandonscore"
mandatory=true
versionRange="[3.2.1.+,)"
ordering="AFTER"
side="BOTH"
[[dependencies.hussein]]
modId="draconicevolution"
mandatory=true
versionRange="[3.1.2.598,)"
ordering="AFTER"
side="BOTH"